#define MAX_FILE_NAME 32
#define MAX_FILE_SIZE 351*1024
#define MAX_DIR_NUM 128

#define TOTAL_SIZE 16*1024*1024

#define START 1
#define FILE_DIR_START 2
#define FILE_DIR_BITMAP_START 130
#define INODE_BITMAP_START 131
#define BLOCK_BITMAP_START 132
#define INODE_START 134
#define BLOCK_START 390


#define BLOCK_NUM 16384
#define BLOCK_SIZE 1024

#define DISK_INODE_NUM 1024*4
#define FILE_INODE_NUM 28
#define DISK_INODE_SIZE 64

#define NO_ERROR 1
#define ERROR_VM_NOEXIST 2
#define ERROR_LOAD_SUPER_FAIL 3
#define ERROR_UPDATE_INODE_FAIL 4
#define ERROR_INPUT_OUT_OF_RANGE 5
#define ERROR_BLOCK_READ 6
#define ERROR_BLOCK_WRITE 7
#define ERROR_READ_BITMAP 8
#define ERROR_WRITE_BITMAP 9
#define ERROR_INSUFFICIENT_FREE_INODE 10
#define ERROR_INODEID_ALREADY_IN_USE 11
#define ERROR_INSUFFICIENT_FREE_BLOCKS 12
#define ERROR_BLOCKID_ALREADY_IN_USE 13
#define NOT_A_DIR -1
#define CAN_NOT_MAKE_MORE_DIR -2
